/* do not change this file, it is auto generated by storybook. */

import {
    configure,
    addDecorator,
    addParameters,
    addArgsEnhancer,
    clearDecorators,
} from '@storybook/react-native';

import { decorators, parameters } from './preview';

if (decorators) {
    if (__DEV__) {
        // stops the warning from showing on every HMR
        clearDecorators();
    }
    decorators.forEach((decorator) => addDecorator(decorator));
}

if (parameters) {
    addParameters(parameters);
}

try {
    configure(() => {
        require('../src/features/clues-creation/views/components/ProgressAnimation.stories.tsx');
    }, module, false);
} catch (e) {
    console.error(e);
}

const getStorybookUI = () => null;
export const view = { getStorybookUI };
